ALTER TABLE Student
ADD
CONSTRAINT S_Prim PRIMARY KEY clustered(Sno),
CONSTRAINT Ssex_Chk CHECK(Ssex IN ('ÄÐ','Å®')),
CONSTRAINT Sage_Chk CHECK(Sage BETWEEN 14 AND 65)
GO
ALTER TABLE Course
ADD
CONSTRAINT C_Prim PRIMARY KEY clustered(Cno),
CONSTRAINT Credit_Chk CHECK(Credit IN (1,2,3,4,5,6))
GO
ALTER TABLE Class
ADD
CONSTRAINT Cl_Prim PRIMARY KEY clustered(Clno),
CONSTRAINT Num_Chk CHECK(Number BETWEEN 1 AND 100),
CONSTRAINT Cl_Fore FOREIGN KEY(Monitor) REFERENCES Student(Sno)
GO
ALTER TABLE Grade
ADD
CONSTRAINT Grade_Fore1 FOREIGN KEY(Sno) REFERENCES Student(Sno),
CONSTRAINT Grade_Fore2 FOREIGN KEY(Cno) REFERENCES Course(Cno),
CONSTRAINT Grade_Chk CHECK(Gmark BETWEEN 0 AND 100)
GO
ALTER TABLE Student
ADD
CONSTRAINT Stu_Fore1 FOREIGN KEY(Clno) REFERENCES Class(Clno)
GO
